### PR TITLE
Bump rust-toolchain to a modern version

### PR DESCRIPTION
**Pull request by davidrusu**
Hi, I was looking to do some work on this code-base but noticed we are on a fairly old version of rust-nightly.

This PR changes:
- `#![feature(external_doc)]` has stabilized and changed to `[doc = include_str!(...)`
- `#![feature(try_trait)]` has been stabilized
- bump rust-toolchain from `nightly-2019-07-31` to `nightly-2021-11-22`

### CODE REVIEW

**Comment by rubdos** [comment]
Related to https://github.com/dalek-cryptography/curve25519-dalek/pull/372

**Comment by davidrusu** [comment]
@rubdos from what I can tell, development has moved to https://github.com/zkcrypto/bulletproofs

**Comment by rubdos** [comment]
> This crate continues the curve25519-dalek series under a different package name. Unfortunately, one of the maintainers of the previous crate seized control of the dalek-cryptography GitHub organization and the subtle and curve25519-dalek crates by silently removing all other co-maintainers.

Damnit.

**Comment by davidrusu** [comment]
:confused: The cryptography is exciting enough, the dramatics are not necessary!

**Comment by rubdos** [comment]
I agree. I'll silently protest to rename zkcrypto/curve25519-dalek-ng to zkcrypto/curve25519-weeping-angels.

**Pull request closed without merging**
