### PR TITLE
Update nightly pin and doc include paths.

### LINKED ISSUE #283: Incorrect path for doc include range proof
Seems I'm having some problems to evaluate the path for the doc includes with the latest Rust.

```
error: couldn't read src/range_proof/../docs/range-proof-protocol.md: No such file or directory (os error 2)
 --> src/range_proof/mod.rs:2:18
  |
2 | #![doc(include = "../docs/range-proof-protocol.md")]
  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ couldn't read file
```

The absolute path should consider one more level. Here is a pull request that fixes it.
https://github.com/dalek-cryptography/bulletproofs/pull/282

### PR DESCRIPTION
**Pull request by hdevalence**
Closes #283
Closes #282
Closes #290

### CODE REVIEW

**Comment by hdevalence** [comment]
(This clobbers the one-liner PR in #282 but without making those changes simultaneously with the version bump the CI will break).

**Comment by hdevalence** [comment]
(Crossref: these changes are required because of https://github.com/rust-lang/rust/pull/60938 )

**Comment by hdevalence** [comment]
After merging this we should probably do a point release, since the currently-released version is broken on nightlies going forward.  WDYT @oleganza ?

**Comment by oleganza** [comment]
Sure!

**Pull request merged**
