### PR TITLE
Add benchmarks for BulletproofGens and PedersenGens

### PR DESCRIPTION
**Pull request by rubdos**
I noticed BulletproofGens is quite slow with larger generator sizes. This commit adds a benchmark for both generators. Figured it may come in handy some day.

### CODE REVIEW

**Comment by oleganza** [comment]
Thank you!

Yeah, making generators is slow, that's why APIs allow you to pass a precomputed instance around, so you can reuse it as long as the process lives.

Do you mind running `cargo fmt` to make Travis CI happy?

**Comment by rubdos** [comment]
> Yeah, making generators is slow, that's why APIs allow you to pass a precomputed instance around, so you can reuse it as long as the process lives.

Makes me wonder; would it be useful to have some standard-sized precomputed at compile time? That way, we don't need to initialize them on potentially slower devices.

**Comment by rubdos** [comment]
Maybe I should add some benches for the internal generators too?

**Comment by oleganza** [comment]
>Makes me wonder; would it be useful to have some standard-sized precomputed at compile time? That way, we don't need to initialize them on potentially slower devices.

Is it slow enough to make booting up a process uncomfortably slow? If you use a small device as a network node that validates a lot of proofs, then it can create an instance of generators with a necessary capacity upfront and then reuse it. Does it matter if it took a second or two to generate it?

**Comment by oleganza** [comment]
>Maybe I should add some benches for the internal generators too?
WDYM?

**Comment by rubdos** [comment]
> Is it slow enough to make booting up a process uncomfortably slow? If you use a small device as a network node that validates a lot of proofs, then it can create an instance of generators with a necessary capacity upfront and then reuse it. Does it matter if it took a second or two to generate it?

Nah, I suppose not. If it does hurt me some day, I'll come back to it.

>> Maybe I should add some benches for the internal generators too?
> WDYM?

Meant to add a benchmark for `AggregatedGensIter`, but that doesn't actually compute anything significant.

For me this is finished for now :-)

**Comment by oleganza** [comment]
On my 3.1 GHz Intel Core i7, I get **256** generators created in **5.1 ms**. This means, something like a SHA256 circuit (~25K multiplication gates => 25K generator pairs) would take **0.5 sec**. Even if it's 2-3x slower, it's still pretty fast for a one-time boot cost even for such a big circuit.

At the same time, the cost of validating each proof with such a circuit size would be higher than making the necessary amount of generators, so the marginal cost of creating them upfront becomes negligible after just a handful of proofs.

**Comment by oleganza** [comment]
I've changed the base branch to `develop`, this is where all the new patches are going to. `main` contains stable releases only.

**Comment by rubdos** [comment]
> I've changed the base branch to `develop`, this is where all the new patches are going to. `main` contains stable releases only.

Woop, sorry! My bad; I knew that :-)

**Comment by rubdos** [comment]
> On my 3.1 GHz Intel Core i7, I get **256** generators created in **5.1 ms**. This means, something like a SHA256 circuit (~25K multiplication gates => 25K generator pairs) would take **0.5 sec**. Even if it's 2-3x slower, it's still pretty fast for a one-time boot cost even for such a big circuit.

docs say:
> `gens_capacity` is the number of generators to precompute for each party. For rangeproofs, it is sufficient to pass 64, the maximum bitsize of the rangeproofs. For circuit proofs, the capacity must be greater than the number of multipliers, rounded up to the next power of two.

So for 25k, that gives a `gens_capacity` of 32768. Criterion wants to take >1h to benchmark this... Anyhow: my threadripper measures 739.08 ms ± 6ms.

**Comment by oleganza** [comment]
Oh, i forgot about rounding up. But on the other hand, we can fix it: https://github.com/dalek-cryptography/bulletproofs/issues/198

**Pull request merged**
